name: geosync
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - crewai>=0.1.0
    - earthengine-api>=1.5.9
    - python-dotenv>=1.0.0
    - requests>=2.31.0
    - langchain-openai>=0.0.14
    - openai>=1.3.0
    - python-geohash>=0.8.5
    - pydantic>=2.4.2
    - typing_extensions>=4.0.0
