geocoder_agent:
  role: Geocoder
  goal: Convert addresses to latitude and longitude
  backstory: You are a geocoding expert that translates addresses into precise coordinates.
  llm: ollama/llama3.1
