geocode_task:
  description: >
    Your input address for this task is: {address}. 
    Use the 'Geoapify Geocoder' tool to convert this address to coordinates.
    Provide the address string {address} directly as the value for the 'address' argument required by the tool.
  expected_output: "Latitude and longitude of the address in JSON format."
  agent: geocoder_agent
  output_key: coordinates

fetch_satellite_image_task:
  description: >
    You need to extract latitude and longitude from the JSON string provided by the geocoder_agent. 
    Parse the JSON string first, then use the lat and lon values to fetch satellite images of the same location, from {first_date} and {second_date}.
    Input JSON: {{ coordinates }}
  expected_output: A JSON with image_path_1 and image_path_2 fields, pointing to the saved GeoTIFFs.
  agent: satellite_image_agent
  dependencies:
    - geocode_task
  input:
    coordinates: "{{ tasks.geocode_task.output }}"
  output_key: satellite_images_paths

analyze_image_differences_task:
  description: >
    Analyze the two satellite images saved in raw_images and create a visual difference map.
  expected_output: A raster image showing the differences between the two satellite captures.
  agent: image_analysis_agent
  dependencies:
    - fetch_satellite_image_task
  input:
    image_path_1: "{{ tasks.fetch_satellite_image_task.output.image_path_1 }}"
    image_path_2: "{{ tasks.fetch_satellite_image_task.output.image_path_2 }}"
